// Finalised hash32 with a seed — different seeds produce independent outputs
// so X and Y coordinates are uncorrelated even for identical input strings.
function hash32(input: string, seed: number): number {
  let h = (seed ^ 0x9e3779b9) >>> 0
  for (let i = 0; i < input.length; i++) {
    h = Math.imul(h ^ input.charCodeAt(i), 0x9e3779b9) >>> 0
    h ^= h >>> 16
  }
  h = Math.imul(h ^ (h >>> 15), 0x85ebca6b) >>> 0
  h ^= h >>> 13
  h = Math.imul(h ^ (h >>> 16), 0xc2b2ae35) >>> 0
  return h / 0xffffffff // [0, 1)
}

function clamp(value: number, min: number, max: number): number {
  return Math.min(max, Math.max(min, value))
}

import type { PageIntent } from '@/lib/core/types'

export function getStubSummary(title: string): string {
  const clean = title.trim()
  if (clean.length === 0) return 'No summary yet. This article preview will be generated by AI soon.'
  return clean.length > 100 ? `${clean.slice(0, 100)}...` : `${clean}...`
}

export function getStubReadingTime(title: string): number {
  return Math.max(1, Math.ceil(title.length / 5))
}

export function getStubIsAlive(): boolean {
  return true
}

/** Fallback intent when LLM hasn't classified this URL yet. */
export function getStubIntent(_url: string, _title: string): PageIntent | undefined {
  return undefined
}

export function getThumbnailPlaceholder(domain: string): { label: string; icon: string } {
  return {
    label: domain || 'unknown',
    icon: '🖼',
  }
}

export function urlToCoords(url: string, category?: string): [number, number] {
  const categoryKey = category?.trim() || 'uncategorized'

  // Seeds 1/2 for category center, 3/4 for per-URL offset — all independent
  const centerX = 0.15 + hash32(categoryKey, 1) * 0.7
  const centerY = 0.15 + hash32(categoryKey, 2) * 0.7
  const offsetX = (hash32(url, 3) - 0.5) * 0.25
  const offsetY = (hash32(url, 4) - 0.5) * 0.25

  return [
    clamp(centerX + offsetX, 0, 1),
    clamp(centerY + offsetY, 0, 1),
  ]
}

export function colorFromKey(input: string): string {
  const hue = Math.floor(hash32(input, 5) * 360)
  return `hsl(${hue} 65% 55%)`
}
