import { Database, Zap } from 'lucide-react'
import type { ViewProps } from '@/components/views/types'
import { Button } from '@/components/ui/button'

export function KnowledgeSettingsView({ onRunTags }: ViewProps) {
  return (
    <div className="max-w-4xl space-y-6 py-4">
      <div className="space-y-4">
        <h3 className="text-sm font-semibold uppercase tracking-wide text-muted-foreground">Domain Knowledge Base</h3>
        
        <div className="rounded-lg border border-border bg-card/50 p-6 space-y-6">
          <div className="flex gap-4">
            <div className="shrink-0 p-2 rounded-md bg-primary/10 text-primary">
              <Zap className="h-6 w-6" />
            </div>
            <div className="space-y-1">
              <p className="text-sm font-medium">Layer 0: Static Prefill</p>
              <p className="text-xs text-muted-foreground leading-relaxed">
                TabLab comes with a pre-baked knowledge base of ~200 popular domains. 
                This allows for instant site description and platform detection without any LLM calls.
              </p>
            </div>
          </div>

          <div className="flex gap-4">
            <div className="shrink-0 p-2 rounded-md bg-secondary/10 text-secondary">
              <Database className="h-6 w-6" />
            </div>
            <div className="space-y-1">
              <p className="text-sm font-medium">Domain Descriptions (Cache)</p>
              <p className="text-xs text-muted-foreground leading-relaxed">
                For domains not in Layer 0, descriptions are generated by an LLM and stored in your local IndexedDB. 
                These descriptions help the AI categorize pages more accurately.
              </p>
            </div>
          </div>
        </div>

        <div className="bg-amber-500/10 border border-amber-500/20 rounded-lg p-4">
          <p className="text-xs text-amber-500 font-medium mb-1">Coming Soon</p>
          <p className="text-[11px] text-amber-500/80">
            Internal editor for domain descriptions and custom platform rules.
          </p>
        </div>

        <div className="flex justify-start">
          <Button variant="outline" onClick={() => alert('Use AI Actions -> Domains for now')}>
            Re-scan Domains
          </Button>
        </div>
      </div>
    </div>
  )
}
